### ISSUE TITLE
Can sha256 be used

### ISSUE THREAD

**Issue by gdamjan** [electrickite/mkinitcpio-tpm2-encrypt#3]
of course I don't even know if it makes a difference cryptographically, but on my Ryzen PC with fTPM `tpm2_pcrread` reports both sha1 and sha256 PCR values.

**Comment by gdamjan** [comment]
More specifically, I'm asking for the `tpmpcr` setting here 
https://github.com/electrickite/mkinitcpio-tpm2-encrypt#tpmpcr

**Comment by electrickite** [comment]
Yes, just use `sha256` in your bank specifier, ex: `tpmpcr=sha256:0,2,7`

Each bank specifier is passed as-is to either the `tpm2_unseal` or `tpm2_nvread` command, depending on your configuration.

**Comment by gdamjan** [comment]
thanks

perhaps this can be added as a footnote to the tpmpcr paragraph.
